#
# Steam 'n' Rails
# Copyright (c) 2024 The Railways Team
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

org.gradle.jvmargs = -Xmx3G
org.gradle.caching = true

# Mod Info
archives_base_name = Steam_Rails
mod_version = 1.6.15-beta
maven_group = com.railwayteam.railways

minecraft_version = 1.21.1

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version = 2024.11.17

# Fabric
# https://fabricmc.net/develop/
fabric_loader_version = 0.18.4
fabric_api_version = 0.116.7+1.21.1

# NeoForge
# https://neoforged.net/
forge_version = 21.1.218

# Create - Fabric
# Not updated yet - TODO essential update
# https://modrinth.com/mod/create-fabric/versions
create_fabric_version = 6.0.8.0+build.1734-mc1.20.1
create_fabric_version_range = >=6.0.7

# Create - Forge
# https://github.com/Creators-of-Create/Create/wiki/Depending-on-Create
create_forge_version = 6.0.9-215
create_forge_version_range = [6.0.7,)
ponder_version = 1.0.81
registrate_forge_version = MC1.21-1.3.0+67
flywheel_version = 1.0.6

# Mixin Extras
# https://github.com/LlamaLad7/MixinExtras
mixin_extras_version = 0.3.5

# Development QOL
# Create Fabric supports all 3 recipe viewers: JEI, REI, and EMI. This decides which is enabled at runtime.
# set to disabled to have none of them.
fabric_recipe_viewer = emi
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files
jei_fabric_version = 19.27.0.340
# JEI 10+ seems to have issues on Forge, so the versions must be different for now. # 1.19 edit: no version < 11 exists, so use that
jei_forge_version = 11.6.0.1015
# REI - https://modrinth.com/mod/rei/versions
rei_version = 16.0.799
# EMI - https://modrinth.com/mod/emi/versions (https://maven.terraformersmc.com/releases/dev/emi/emi-fabric)
emi_version = 1.1.22+1.21.1

# Mod Menu - https://modrinth.com/mod/modmenu/versions
modmenu_version = 11.0.3
# LazyDFU - https://modrinth.com/mod/lazydfu/versions
# Not updated - may never be?
lazydfu_version = null
enable_ldfu = false

# Mod compatibility

# Simple Voice Chat - https://modrepo.de/minecraft/voicechat/api/getting_started
# https://modrinth.com/plugin/simple-voice-chat
voicechat_version = 1.21.1-2.6.11
voicechat_api_version = 2.6.0
# https://maven.maxhenkel.de/#/releases/de/maxhenkel/voicechat/voicechat-api
enable_simple_voice_chat = false

# Hex Casting
# https://modrinth.com/mod/hex-casting/versions
# Not updated yet
hexcasting_version = 0.10.3
# https://modrinth.com/mod/paucal/versions
paucal_version = 0.7.1-pre-26
# https://modrinth.com/mod/patchouli/versions
patchouli_version = 92
# https://modrinth.com/mod/pehkui/versions
pehkui_version = 3.8.3
# https://modrinth.com/mod/kotlin-for-forge/versions
kotlin_for_forge_version = 5.10.0
enable_hexcasting = false

# Oh The Biomes You'll Go
# https://modrinth.com/mod/biomesyougo/versions
# Not updated yet
byg_version = null
# https://modrinth.com/mod/terrablender/versions
terrablender_version_forge = xjrV1Uvq
terrablender_version_fabric = chxo508B
# https://modrinth.com/mod/geckolib/versions
#geckolib_version_fabric = 5bofFrdJ
# https://modrinth.com/mod/corgilib/versions
#corgilib_version_fabric = 1.20.1-4.0.0.0-fabric
enable_byg = false

# Biomes O' Plenty
# https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty/files
bop_version = 7251965
enable_bop = false

# Natures Spirit
# https://modrinth.com/mod/natures-spirit
natures_spirit_version = TRMapjpU
enable_natures_spirit = false

# Create: Dreams and Desires
# https://modrinth.com/mod/create-dreams-and-desires
dnd_version = P4yXqsnw
enable_dnd = false

# Quark
# Not updated yet
# https://maven.blamejared.com/org/violetmoon/quark/Quark/
# https://maven.blamejared.com/org/violetmoon/zeta/Zeta/
quark_version = 4.0-436.3287
zeta_version = 1.0-14.60
enable_quark = false

# Terrafirmacraft
# https://modrinth.com/mod/terrafirmacraft
tfc_version = 4.0.16-beta
enable_tfc = false

# Rubidium / Sodium / Iris
# https://modrinth.com/mod/rubidium/versions
# Not updated yet
rubidium_version = 0.6.5
# https://modrinth.com/mod/sodium/versions
sodium_version = mc1.21.1-0.6.13
# https://modrinth.com/mod/indium/versions
indium_version = 1.0.35+mc1.21
# https://modrinth.com/mod/iris/versions
iris_version = 1.8.8+1.21.1
enable_sodium_rubidium = false
enable_iris = false

# Tweakeroo
# https://www.curseforge.com/minecraft/mc-mods/malilib/files
malilib_version = 5647783
# https://www.curseforge.com/minecraft/mc-mods/tweakeroo/files
tweakeroo_version = 5647797
enable_tweakeroo = false

# Security Craft
# https://www.curseforge.com/minecraft/mc-mods/security-craft/files/
sc_version = 7148568
enable_sc = false

# Publishing
# Modrinth
modrinth_id = ZzjhlDgM
# Curseforge
curseforge_id = 688231